#!/bin/bash

DOTFILE_PROJECTS=(
    "sway"
    "ghostty"
    "zsh"
    "tmux"
    "nvim"
##xorg dotfiles
    #"i3"
    #"polybar"
    #"picom"
)

for project in "${DOTFILE_PROJECTS[@]}"; do
    echo "Installing $project configuration..."
    stow -D "$project"
    stow -v "$project"
done

