#!/bin/bash 

INSTALL_RUST=${}

# install distro specific packages
if grep -Fq "ubuntu" /etc/os-release; then
    echo "Got Ubuntu"
    . ./scripts/ubuntu
else
    echo "Unsupported Distro :("
    exit
fi

echo "Adding current user to docker group..."
sudo usermod -aG docker $USER

# for brightnessctl
echo "Adding current user to video group..."
sudo usermod -aG video $USER

# Install Rust?
./scripts/prompt "curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh" "Install Rust"

# install ohmyzsh and plugins
. ./scripts/ohmyzsh

. ./install_dotfiles

chsh -s $(which zsh)

