#!/bin/bash

sudo apt-get update && sudo apt-get install -y

# generic shite

sudo apt-get install -y curl gpg ca-certificates apt-transport-https \ 
  gcc g++ make cmake wget build-essential autoconf autogen


packages=(
    xorg
    lightdm
    i3
    snap
    stow
    tmux
    zsh
    flameshot
    neofetch
    ripgrep
    fd-find
    xclip
    picom             # enable transparency in i3
    feh               # background picker for i3
    brightnessctl     # name gives it away
    rofi
    pulseaudio-utils
    polybar           # nicer statusbar
    caffeine          # no sleep 
)

# Update package list
sudo apt-get update

# Install all packages
sudo apt-get install -y "${packages[@]}"

sudo snap install neovim --classic
sudo snap install spotify 

# install ghostty 
#sudo snap install ghostty --classic
sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)" # snap install didnt work with nvidia gpu :( 

# docker
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

